# -*- coding: utf-8 -*-
"""traductor_a_F.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-U33bsbg7LyoVhwmvQB1b4VkZ5gnjuu
"""


def mujeres(lista):
    m=0
    for i in range(len(lista)):
        lista[i]=lista[i].lower()
        if(lista[i]=="mujer"):
            m=m+1
    return m
def hombres(lista):
    h=0
    for i in range(len(lista)):
        lista[i]=lista[i].lower()
        if(lista[i]=="hombre"):
            h=h+1
    return h

MH = ['hombre', 'mujer', 'MUJER', 'HOMBRE', 'MUJER','hombre', 'mujer', 'MUJER', 'HOMBRE', 'MUJER']
print("El numero de mujeres es:",mujeres(MH))
print("El numero de hombres es:",hombres(MH))